# -*- coding: utf-8 -*-
"""assignments_one.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17CPHVGGz5zIinPlrH9-6qVPSzyB0SNVh

<img src="https://i.redd.it/6brfmxf7b8ga1.png" alt="Italian Trulli">

### Exercise on data types

## <font color='red'>What data type would that be?</font>

#### x = 5
#### print(type(x))
"""

x=5
print(type(x))

"""#### x = "Hello World"
#### print(type(x))

"""

x="hello world"
print(type(x))

"""#### x = 20.5
#### print(type(x))
"""

x=20.5
print(type(x))

"""#### x = ["apple", "banana", "cherry"]
#### print(type(x))
"""

x=["apple","banana0,","cherry"]
print(type(x))

"""#### x = ("apple", "banana", "cherry")
#### print(type(x))
"""

x=("apple","banana","cherry")
print(type(x))

"""#### x = {"name" : "John", "age" : 36}
#### print(type(x))
"""

x={"name":"john",'age':"36"}
print(type(x))

"""#### x = True
#### print(type(x))
"""

x=True
print(type(x))

"""## Exercise on Numbers

#### Insert the correct syntax to convert x into a floating point number.
"""

# x = 5
# x =....(x)
# print(x)

x=5.5
print(x)

"""### Insert the correct syntax to convert x into a integer.


"""

# x = 5.5
# x =......(x)
# print(x)

x=5
print(x)

"""## Exercise on string

### Use the `len()` function to print the length of the string.
"""

# x = "Hello World"
# print(.........)

"""### Get the first character of the string txt.


"""

# txt = "Hello World"
# x = ..........

txt="Hello World"
print(txt[0])

"""### Get the characters from index 2 to index 4 (llo).


"""

# txt = "Hello World"
#  x =........

txt="Hello World"
print(txt[2:5:1])

"""##### Return the string without any whitespace at the beginning or the end.
##### hint ` txt.strip()`

"""

# txt = " Hello World "
# x =..................

txt="Hello World"
print(txt.strip())

"""### Convert the value of `txt` to upper case.


"""

# txt = "Hello World"
# txt = ........

txt="Hello World"
print(txt.upper())

"""### Convert the value of `txt` to lower case.


"""

# txt = "Hello World"
# txt = .........

txt="Hello World"
print(txt.lower())

"""#### Replace the character` H` with a `J`"""

# txt = "Hello World"
# txt = txt. .......(...,... )

txt="Hello World"
print(txt.replace("H","J"))

"""#### Insert the correct syntax to add a placeholder for the age parameter.


"""

# age = 36
# txt = f"My name is John, and I am ......"
# print(txt)

age=36
print(f"my name is John, and i am {age}")

"""### Exercise on Booleans

The statement below would print a Boolean value, which one?
"""

# print(10 > 9)
# true

"""The statement below would print a Boolean value, which one?


"""

# print(10 == 9)
# false

"""The statement below would print a Boolean value, which one?


"""

# print(10 < 9)
# false

"""### <font color='gold'>Exercise-1</font>

#### Write a Python program to print the following string in a specific format
"""

# Twinkle, twinkle, little star,
# 	How I wonder what you are!
# 		Up above the world so high,
# 		Like a diamond in the sky.
# Twinkle, twinkle, little star,
# 	How I wonder what you are!

print("Twinkle, tinkle, little star,")
print("\tHow  wonder what you are!")
print("\t\tUp above the world so high,")
print("\t\tLike a diamond in the sky.")
print("Twinkle, twinkle, little star,")
print("\tHow I wonder what you are!")

"""### <font color='gold'>Exercise-2</font>

#### Write a Python program that print the user's first and last name and prints them in reverse order with a space between them.
"""

fname="ziad"
lname="hamdy"
print(f"{lname} {fname}")

"""### <font color='gold'>Exercise-3</font>

#### Write a Python program that calculates the area of a circle and radius = 1.1
"""

radius=1.1
area= math.pi * radius ** 2
print(area)

"""### <font color='gold'>Exercise-4</font>

#### Write a Python program that accepts a filename from the user and prints the extension of the file.

Sample Output:
Input the Filename: abc.java                                                                                  
The  extension of the file is : 'java'
"""

filename="abc.py"
f_exts=filename.split(".")
print(f_exts[-1])

filename="abc.java"
f_exts=filename.split(".")
print(f_exts[-1])

"""### <font color='gold'>Exercise-5</font>

#### Covert from string to list and tuple value ="Amit"
"""

name="Amit"
listn=list(name)
tuplen=tuple(name)
print(listn)
print(tuplen)

"""## After that

### Relace the index 3 in the list

### Convert the list to string and print the list
"""

listn=['A', 'm', 'i', 't']
stringn=''.join(listn)
print(stringn)

"""### <font color='gold'>Exercise-6</font>

#### Write a Python program to display the first and last colors from the following list.

#### color_list = ["Red","Green","White" ,"Black"]

<img src="https://www.w3resource.com/w3r_images/python-basic-image-exercise-8.png" alt="Italian Trulli">
"""

colorl=["Red","Green","White" ,"Black"]
Fcolor=colorl[0]
Lcolor=colorl[-1]
print(f"{Fcolor},{Fcolor}")

"""## <font color='gold'>Exercise-7</font>

#### Write a Python program to print the following 'here document'.
"""

#Sample Output:
# a string that you "don't" have to escape
# This
# is a  ....... multi-line
# heredoc string --------> example

"""## <font color='gold'>Exercise- 8</font>

###### I need to  check if  link `https://www.google.com/` strart with https or not and if the ` aimt4536@gmail.com` end with .com
"""

name="https://www.google.com/"
print(name.startswith("https"))

name="aimt4536@gmail.com"
print(name.endswith(".com"))

"""# Thanks ❤

<img src="https://pbs.twimg.com/media/ELwC6EgXYAE8AtN.jpg" alt="Italian Trulli">
"""

